# -*- coding: utf-8 -*-
"""Netfkix User .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164N7koy_zdltrWStGWnkX0P3zKtEyFTB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.titleweight'] = 'bold'

print("✅ Libraries imported successfully")

df = pd.read_csv('netflix_users.csv')

print("Shape       :", df.shape)
print("Columns     :", list(df.columns))
print("\nFirst 5 rows:")
df.head()

print("Missing values:\n", df.isnull().sum())
print(f"\nDuplicate rows: {df.duplicated().sum()}")

df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

df['Last_Login'] = pd.to_datetime(df['Last_Login'])

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0, 18, 25, 35, 50, 100],
    labels=['Under 18', '18-25', '25-35', '35-50', '50+']
)

cutoff = df['Last_Login'].max() - timedelta(days=30)
df['Status'] = df['Last_Login'].apply(
    lambda x: 'Active' if x >= cutoff else 'Inactive'
)

print("\n✅ Cleaning done. New shape:", df.shape)
print("New columns added : Age_Group, Status")
df[['Age', 'Age_Group', 'Last_Login', 'Status']].head()

print("=" * 45)
print("Age Statistics")
print("=" * 45)
print(df['Age'].describe().round(2))

print("\n" + "=" * 45)
print("Subscription Type Counts")
print("=" * 45)
print(df['Subscription_Type'].value_counts())

print("\n" + "=" * 45)
print("Favorite Genre Counts")
print("=" * 45)
print(df['Favorite_Genre'].value_counts())

print("\n" + "=" * 45)
print("Top 5 Countries")
print("=" * 45)
print(df['Country'].value_counts().head())

print("\n" + "=" * 45)
print("Avg Watch Time by Subscription Type")
print("=" * 45)
print(df.groupby('Subscription_Type')['Watch_Time_Hours'].mean().round(2))

plt.figure(figsize=(10, 5))
sns.histplot(df['Age'], bins=25, kde=True, color='steelblue')
plt.title('Age Distribution of Netflix Users')
plt.xlabel('Age')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
order = df['Subscription_Type'].value_counts().index
ax = sns.countplot(x='Subscription_Type', data=df, order=order, palette='Blues_d')
plt.title('Subscription Type Distribution')
plt.xlabel('Subscription Type')
plt.ylabel('Number of Users')
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=11)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
watch_avg = df.groupby('Subscription_Type')['Watch_Time_Hours'].mean().sort_values()
ax = watch_avg.plot(kind='barh', color='coral')
plt.title('Average Watch Time (Hours) by Subscription Type')
plt.xlabel('Avg Watch Time (Hours)')
for i, v in enumerate(watch_avg):
    ax.text(v + 0.1, i, f'{v:.1f}h', va='center', fontsize=11)
plt.tight_layout()
plt.show()

plt.figure(figsize=(11, 5))
genre_counts = df['Favorite_Genre'].value_counts()
sns.barplot(x=genre_counts.index, y=genre_counts.values, palette='Set2')
plt.title('Favorite Genre Distribution')
plt.xlabel('Genre')
plt.ylabel('Number of Users')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
genre_watch = df.groupby('Favorite_Genre')['Watch_Time_Hours'].mean().sort_values()
ax = genre_watch.plot(kind='barh', color='mediumpurple')
plt.title('Average Watch Time by Favorite Genre')
plt.xlabel('Avg Watch Time (Hours)')
for i, v in enumerate(genre_watch):
    ax.text(v + 0.1, i, f'{v:.1f}h', va='center', fontsize=10)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
top_countries = df['Country'].value_counts().head(10)
sns.barplot(x=top_countries.values, y=top_countries.index, palette='viridis')
plt.title('Top 10 Countries by Number of Users')
plt.xlabel('Number of Users')
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
pivot = df.groupby(['Age_Group', 'Subscription_Type']).size().unstack(fill_value=0)
sns.heatmap(pivot, annot=True, fmt='d', cmap='YlOrRd', linewidths=0.5)
plt.title('Age Group vs Subscription Type')
plt.xlabel('Subscription Type')
plt.ylabel('Age Group')
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 5))
status_counts = df['Status'].value_counts()
plt.pie(status_counts,
        labels=status_counts.index,
        autopct='%1.1f%%',
        startangle=90,
        colors=['#2ecc71', '#e74c3c'])
plt.title('Active vs Inactive Users (Last 30 Days)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 5))
numeric_df = df.select_dtypes(include=np.number)
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm',
            fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap (Numeric Features)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
sns.boxplot(x='Subscription_Type', y='Watch_Time_Hours',
            data=df, palette='pastel')
plt.title('Watch Time Distribution by Subscription Type')
plt.xlabel('Subscription Type')
plt.ylabel('Watch Time (Hours)')
plt.tight_layout()
plt.show()

top_sub          = df['Subscription_Type'].value_counts().idxmax()
top_genre        = df['Favorite_Genre'].value_counts().idxmax()
top_country      = df['Country'].value_counts().idxmax()
avg_age          = df['Age'].mean()
avg_watch        = df['Watch_Time_Hours'].mean()
active_pct       = (df['Status'] == 'Active').mean() * 100
most_watch_sub   = df.groupby('Subscription_Type')['Watch_Time_Hours'].mean().idxmax()
most_watch_genre = df.groupby('Favorite_Genre')['Watch_Time_Hours'].mean().idxmax()

print("=" * 50)
print("        KEY INSIGHTS SUMMARY")
print("=" * 50)
print(f"  Most popular subscription  : {top_sub}")
print(f"  Most popular genre         : {top_genre}")
print(f"  Top country by users       : {top_country}")
print(f"  Average user age           : {avg_age:.1f} years")
print(f"  Average watch time         : {avg_watch:.1f} hours/month")
print(f"  Active users (last 30d)    : {active_pct:.1f}%")
print(f"  Plan with most watch time  : {most_watch_sub}")
print(f"  Genre with most watch time : {most_watch_genre}")
print("=" * 50)
print("\n✅ Analysis Complete!")